name: mobile_app

environment:
  sdk: '^3.10.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5   # for state management
  # ...other dependencies...
  flutter_local_notifications: ^19.5.0